define(["Ti/_","Ti/_/has","Ti/_/lang"],function(w,x,o){function s(b,d,f){var g=d-10;for(j(b.arg,"String")||(b.arg=""+b.arg);b.arg.length<g;)b.arg=b.rightJustify?b.arg+f:f+b.arg;d-=b.arg.length;b.arg=b.rightJustify?b.arg+f.substring(0,d):f.substring(0,d)+b.arg}function q(b,d){s(b,o.val(d,b.precision),y)}var f=w.assert,j=require.is,r=require.mix,t=x("opera"),y="0000000000",u={b:{base:2,isInt:1},o:{base:8,isInt:1},x:{base:16,isInt:1},X:{extend:["x"],toUpper:1},d:{base:10,isInt:1},i:{extend:["d"]},u:{extend:["d"],
isUnsigned:1},c:{setArg:function(b){if(!isNaN(b.arg)){var d=parseInt(b.arg);f(0>d||127<d,"Invalid character code passed to %c in sprintf");b.arg=isNaN(d)?""+d:String.fromCharCode(d)}}},s:{setMaxWidth:function(b){b.maxWidth="."===b.period?b.precision:-1}},e:{isDouble:1},E:{extend:["e"],toUpper:1},f:{isDouble:1},F:{extend:["f"]},g:{isDouble:1},G:{extend:["g"],toUpper:1}};String.format=function(b){for(var d=o.toArray(arguments),p=/\%(?:\(([\w_]+)\)|([1-9]\d*)\$)?([0 +\-\#]*)(\*|\d+)?(\.)?(\*|\d+)?[hlL]?([\%scdeEfFgGiouxX])/g,
g=[],n,k=0,h,e,i=e=0,m="",v="mapping,intmapping,flags,_minWidth,period,_precision,specifier".split(",");h=p.exec(b);){e=b.slice(e,p.lastIndex-h[0].length);e.length&&g.push(e);if(t){for(e=h.slice(0);e.length<h.length;)e.push(null);h=e}n={};h.slice(1).concat(g.length).map(function(a,b){v[b]&&(n[v[b]]=a)});g.push(n);n[0]&&k++;e=p.lastIndex}e=b.slice(e);e.length&&g.push(e);d.shift();f(!k||d.length,"Format has no mapped arguments");g.forEach(function(a){var c,e={},g,h,l=u[a.specifier];if(j(a,"String"))m+=
a;else{k?f(void 0===d[a.mapping],"Missing key "+a.mapping):(a.intmapping&&(i=parseInt(a.intmapping)-1),f(i<d.length,"Got "+d.length+" format arguments, insufficient for '"+b+"'"));a.arg=d[k?a.mapping:i++];if(!a.compiled){r(a,{compiled:1,sign:"",zeroPad:0,rightJustify:0,alternative:0,minWidth:a._minWidth|0,maxWidth:-1,toUpper:0,isUnsigned:0,isInt:0,isDouble:0,precision:"."===a.period?a._precision|0:1});for(c=a.flags,g=c.length;g--;)switch(e[h=c.charAt(g)]=1,h){case " ":a.sign=" ";break;case "+":a.sign=
"+";break;case "0":a.zeroPad=!e["-"];break;case "-":a.rightJustify=1;a.zeroPad=0;break;case "#":a.alternative=1;break;default:throw Error("Bad formatting flag '"+h+"'");}f(void 0!==l,"Unexpected specifier '"+a.specifier+"'");l.extend&&(r(l,u[l.extend]),delete l.extend);r(a,l)}j(a.setArg,"Function")&&a.setArg(a);j(a.setMaxWidth,"Function")&&a.setMaxWidth(a);"*"===a._minWidth&&(f(k,"* width not supported in mapped formats"),f(isNaN(a.minWidth=parseInt(d[i++])),"The argument for * width at position "+
i+" is not a number in "+this._format),0>a.minWidth&&(a.rightJustify=1,a.minWidth=-a.minWidth));"*"===a._precision&&"."===a.period&&(f(k,"* precision not supported in mapped formats"),f(isNaN(a.precision=parseInt(d[i++])),"The argument for * precision at position "+i+" is not a number in "+this._format),0>a.precision&&(a.precision=1,a.period=""));if(a.isInt)"."===a.period&&(a.zeroPad=0),c=parseInt(a.arg),isFinite(c)||(f(!j(a.arg,"Number"),"Format argument '"+a.arg+"' not an integer; parseInt returned "+
c),c=0),0>c&&(a.isUnsigned||10!=a.base)&&(c=4294967295+c+1),0>c?(a.arg=(-c).toString(a.base),q(a),a.arg="-"+a.arg):(a.arg=c.toString(a.base),c||a.precision?q(a):a.arg="",a.sign&&(a.arg=a.sign+a.arg)),16===a.base&&(a.alternative&&(a.arg="0x"+a.arg),a.arg=a.toUpper?a.arg.toUpperCase():a.arg.toLowerCase()),8===a.base&&a.alternative&&"0"!=a.arg.charAt(0)&&(a.arg="0"+a.arg);else if(a.isDouble){"."!==a.period&&(a.precision=6);c=parseFloat(a.arg);isFinite(c)||(f(!j(a.arg,"Number"),"Format argument '"+a.arg+
"' not a float; parseFloat returned "+c),c=0);switch(a.specifier){case "e":a.arg=c.toExponential(a.precision);break;case "f":a.arg=c.toFixed(a.precision);break;case "g":a.arg=1.0E-4>Math.abs(c)?c.toExponential(0<a.precision?a.precision-1:a.precision):c.toPrecision(a.precision);a.alternative||(a.arg=a.arg.replace(/(\..*[^0])0*/,"$1"),a.arg=a.arg.replace(/\.0*e/,"e").replace(/\.0$/,""));break;default:throw Error("Unexpected double notation '"+a.doubleNotation+"'");}a.arg=a.arg.replace(/e\+(\d)$/,"e+0$1").replace(/e\-(\d)$/,
"e-0$1");t&&(a.arg=a.arg.replace(/^\./,"0."));a.alternative&&(a.arg=a.arg.replace(/^(\d+)$/,"$1."),a.arg=a.arg.replace(/^(\d+)e/,"$1.e"));0<=c&&a.sign&&(a.arg=a.sign+a.arg);a.arg=a.toUpper?a.arg.toUpperCase():a.arg.toLowerCase()}0<=a.maxWidth&&a.arg.length>a.maxWidth?a.arg.substring(0,a.maxWidth):a.zeroPad?q(a,a.minWidth):s(a,o.val(void 0,a.minWidth),"          ");m+=""+a.arg}});return m};return{capitalize:function(b){b=b||"";return b.substring(0,1).toUpperCase()+b.substring(1)},trim:String.prototype.trim?
function(b){return b.trim()}:function(b){return b.replace(/^\s\s*/,"").replace(/\s\s*$/,"")}}});