define("Ti/_/declare,Ti/_/UI/KineticScrollView,Ti/_/style,Ti/_/lang,Ti/UI/MobileWeb/TableViewSeparatorStyle,Ti/UI".split(","),function(n,l,r,s,t,b){var u=r.set,v=require.is,g=s.isDef;return n("Ti.UI.TableView",l,{constructor:function(){var a;this._initKineticScrollView(a=b.createView({width:b.INHERIT,height:b.SIZE,left:0,top:0,layout:b._LAYOUT_CONSTRAINING_VERTICAL}),"vertical","vertical",1);a._add(this._header=b.createView({height:b.SIZE,width:b.INHERIT,layout:b._LAYOUT_CONSTRAINING_VERTICAL}));
a._add(this._sections=b.createView({height:b.SIZE,width:b.INHERIT,layout:b._LAYOUT_CONSTRAINING_VERTICAL}));a._add(this._footer=b.createView({height:b.SIZE,width:b.INHERIT,layout:b._LAYOUT_CONSTRAINING_VERTICAL}));this.data=[]},_handleMouseWheel:function(){this._fireScrollEvent("scroll")},_handleDragStart:function(){this.fireEvent("dragStart")},_handleDrag:function(a){this._fireScrollEvent("scroll",a)},_handleDragEnd:function(a,d,c){var b=this;if(g(c)){var d=c*c/0.001724*(0>c?-1:1),c=Math.abs(c)/
0.0010,f=Math.min(0,Math.max(b._minTranslationY,b._currentTranslationY+d));b.fireEvent("dragEnd",{decelerate:!0});b._animateToPosition(b._currentTranslationX,f,c,"ease-out",function(){b._setTranslation(b._currentTranslationX,f);b._endScrollBars();b._fireScrollEvent("scrollEnd",a)})}},_fireScrollEvent:function(a,d){for(var c,b=0,f=this._contentContainer,i=-this._currentTranslationY,h=this._sections,q=h._children,l=q.length,m=0;m<l;m+=2){var j=q[m],o=i-j._measuredTop,k=j._measuredHeight-o;if(0<o&&0<
k){j=j._rows._children;for(k=1;k<j.length;k+=2){var p=j[k],g=o-p._measuredTop,n=p._measuredHeight-g;0<g&&0<n&&(b++,!c&&(c=p))}}}this.fireEvent(a,{contentOffset:{x:0,y:i},contentSize:{width:h._measuredWidth,height:h._measuredHeight},firstVisibleItem:c,size:{width:f._measuredWidth,height:f._measuredHeight},totalItemCount:this.data.length,visibleItemCount:b,x:d&&d.x,y:d&&d.y})},_defaultWidth:b.FILL,_defaultHeight:b.FILL,_getContentOffset:function(){return{x:-this._currentTranslationX,y:-this._currentTranslationY}},
_handleTouchEvent:function(a,b){var c=0,e=0,f,i=this._sections._children,h=this._tableViewRowClicked,g=this._tableViewSectionClicked;if("click"===a||"singletap"===a){if(h&&g){for(;c<i.length;c+=2)if(f=i[c]._rows._children.indexOf(h),-1!==f){e+=Math.floor(f/2);break}else e+=i[c].rowCount;b.row=b.rowData=h;b.index=e;b.section=g;b.searchMode=!1;l.prototype._handleTouchEvent.apply(this,arguments);this._tableViewSectionClicked=this._tableViewRowClicked=null}}else l.prototype._handleTouchEvent.apply(this,
arguments)},_createSeparator:function(){var a=b.createView({height:1,width:b.INHERIT,backgroundColor:"white"});u(a.domNode,"minWidth","100%");return a},_createDecorationLabel:function(a){return b.createLabel({text:a,backgroundColor:"darkGrey",color:"white",width:b.INHERIT,height:b.SIZE,left:0,font:{fontSize:22}})},_refreshSections:function(){for(var a=0;a<this._sections._children.length;a+=2)this._sections._children[a]._refreshRows();this._triggerLayout()},_calculateLocation:function(a){for(var b=
0,c,e=0;e<this._sections._children.length;e+=2)if(c=this._sections._children[e],b+=c.rowCount,a<b)return{section:c,localIndex:c.rowCount-(b-a)};if(a==b)return{section:c,localIndex:c.rowCount}},_insertRow:function(a,b){var c=this._calculateLocation(b);c&&c.section.add(a,c.localIndex);this._publish(a);this._refreshSections()},_removeRow:function(a){a=this._calculateLocation(a);this._unpublish(a.section._rows._children[2*a.localIndex+1]);a&&a.section._removeAt(a.localIndex)},appendRow:function(a){this._currentSection||
(this._sections._add(this._currentSection=b.createTableViewSection({_tableView:this})),this._sections._add(this._createSeparator()),this.data.push(this._currentSection));this._currentSection.add(a);this._publish(a);this._refreshSections()},deleteRow:function(a){this._removeRow(a)},insertRowAfter:function(a,b){this._insertRow(b,a+1)},insertRowBefore:function(a,b){this._insertRow(b,a)},updateRow:function(a,b){this._removeRow(a);this._insertRow(b,a)},scrollToIndex:function(a){(a=this._calculateLocation(a))&&
this._setTranslation(0,-a.section._measuredTop-a.section._rows._children[2*a.localIndex+1]._measuredTop)},scrollToTop:function(a){this._setTranslation(0,-a)},properties:{data:{set:function(a){if(v(a,"Array")){var d=[];this._sections._removeAllChildren();this._currentSection=void 0;for(var c in a)if(!g(a[c].declaredClass)||"Ti.UI.TableViewRow"!=a[c].declaredClass&&"Ti.UI.TableViewSection"!=a[c].declaredClass)a[c]=b.createTableViewRow(a[c]);for(c=0;c<a.length;c++)"Ti.UI.TableViewRow"===a[c].declaredClass?
(this._currentSection||(this._sections._add(this._currentSection=b.createTableViewSection({_tableView:this})),this._sections._add(this._createSeparator()),d.push(this._currentSection)),this._currentSection.add(a[c])):"Ti.UI.TableViewSection"===a[c].declaredClass&&(a[c]._tableView=this,this._sections._add(this._currentSection=a[c]),this._sections._add(this._createSeparator()),d.push(this._currentSection)),this._publish(a[c]);this._refreshSections();return d}}},footerTitle:{set:function(a,b){b!=a&&
(this._footer._removeAllChildren(),this._footer._add(this._createDecorationLabel(a)));return a}},footerView:{set:function(a,b){b!=a&&(this._footer._removeAllChildren(),this._footer._add(a));return a}},headerTitle:{set:function(a,b){b!=a&&(this._header._removeAllChildren(),this._header._add(this._createDecorationLabel(a)),this._header._add(this._createSeparator()));return a}},headerView:{set:function(a,b){b!=a&&(this._header._removeAllChildren(),this._header._add(a));return a}},maxRowHeight:{post:"_refreshSections"},
minRowHeight:{post:"_refreshSections"},rowHeight:{post:"_refreshSections",value:"50px"},separatorColor:{post:"_refreshSections",value:"lightGrey"},separatorStyle:{post:"_refreshSections",value:t.SINGLE_LINE}}})});