define(["Ti/_/Layouts/Base","Ti/_/declare","Ti/UI","Ti/_/lang","Ti/_/style"],function(y,z,o,A){var s=A.isDef,u=Math.round;return z("Ti._.Layouts.ConstrainingVertical",y,{_doLayout:function(c,e,b,t,h){var k={width:0,height:0},r=c._children,a,j=0,d,n,f,p,l,i,q=[],m=0;l=0;var g=r.length;i=this._measureNode;for(j=0;j<g;j++)a=c._children[j],!a._alive||!a.domNode?this.handleInvalidState(a,c):a._markedForLayout&&((a._preLayout&&a._preLayout(e,b,t,h)||a._needsMeasuring)&&i(a,a,a._layoutCoefficients,this),
d=a._layoutCoefficients,f=d.height,0===f.x2||isNaN(f.x2)?(n=d.width,p=d.sandboxHeight,d=n.x1*e+n.x2,f=f.x1*b+f.x2*(b-m)+f.x3,n=a._getContentSize?a._getContentSize(d,f):a._layout._doLayout(a,isNaN(d)?e:d-a._borderLeftWidth-a._borderRightWidth,isNaN(f)?b:f-a._borderTopWidth-a._borderBottomWidth,isNaN(d),isNaN(f)),isNaN(d)&&(d=n.width+a._borderLeftWidth+a._borderRightWidth),isNaN(f)&&(f=n.height+a._borderTopWidth+a._borderBottomWidth),p=a._measuredSandboxHeight=p.x1*b+p.x2+f,m+=p,a._measuredWidth=d,
a._measuredHeight=f):l++);h=b-m;m=Math.floor(h/l);for(j=0;j<g;j++)a=c._children[j],a._markedForLayout&&(d=a._layoutCoefficients,f=d.height,0!==f.x2&&!isNaN(f.x2)&&(n=d.width,p=d.sandboxHeight,d=n.x1*e+n.x2,f=f.x1*b+f.x2*(j<g-1?m:h-m*(l-1))+f.x3,n=a._getContentSize?a._getContentSize(d,f):a._layout._doLayout(a,isNaN(d)?e:d-a._borderLeftWidth-a._borderRightWidth,isNaN(f)?b:f-a._borderTopWidth-a._borderBottomWidth,isNaN(d),isNaN(f)),isNaN(d)&&(d=n.width+a._borderLeftWidth+a._borderRightWidth),isNaN(f)&&
(f=n.height+a._borderTopWidth+a._borderBottomWidth),a._measuredWidth=d,a._measuredHeight=f,a._measuredSandboxHeight=p.x1*b+p.x2+f));for(j=m=0;j<g;j++)a=c._children[j],a._measuredRunningHeight=m,a._markedForLayout&&(d=a._layoutCoefficients,h=d.sandboxWidth,l=d.top,i=d.left,t&&0!==i.x1?q.push(a):(d=a._measuredWidth,i=a._measuredLeft=i.x1*e+i.x2*d+i.x3,h=a._measuredSandboxWidth=h.x1*e+h.x2+d+(isNaN(i)?0:i),h>k.width&&(k.width=h)),a._measuredTop=l.x1*b+l.x2+m),m+=a._measuredSandboxHeight;k.height=m;g=
q.length;for(j=0;j<g;j++)a=q[j],h=a._layoutCoefficients.sandboxWidth,h=a._measuredSandboxWidth=h.x1*e+h.x2+a._measuredWidth,h>k.width&&(k.width=h);for(j=0;j<g;j++)a=q[j],i=a._layoutCoefficients.left,d=a._measuredWidth,h=a._measuredSandboxWidth,h>k.width&&(k.width=h),i=a._measuredLeft=i.x1*k.width+i.x2*d+i.x3,a._measuredSandboxWidth+=isNaN(i)?0:i;g=r.length;for(j=0;j<g;j++)a=r[j],a._markedForLayout&&(o._elementLayoutCount++,a=r[j],c=a.domNode.style,c.zIndex=a.zIndex,c.left=u(a._measuredLeft)+"px",
c.top=u(a._measuredTop)+"px",c.width=u(a._measuredWidth-a._borderLeftWidth-a._borderRightWidth)+"px",c.height=u(a._measuredHeight-a._borderTopWidth-a._borderBottomWidth)+"px",a._markedForLayout=!1,a.fireEvent("postlayout"));return this._computedSize=k},_getWidth:function(c,e){!s(e)&&2>s(c.left)+s(c.center&&c.center.x)+s(c.right)&&(e=c._defaultWidth);return e===o.INHERIT?c._parent._parent?c._parent._parent._layout._getWidth(c._parent,c._parent.width)===o.SIZE?o.SIZE:o.FILL:o.FILL:e},_getHeight:function(c,
e){!s(e)&&(e=c._defaultHeight);return e===o.INHERIT?c._parent._parent?c._parent._parent._layout._getHeight(c._parent,c._parent.height)===o.SIZE?o.SIZE:o.FILL:o.FILL:e},_isDependentOnParent:function(c){c=c._layoutCoefficients;return!isNaN(c.width.x1)&&0!==c.width.x1||!isNaN(c.height.x1)&&0!==c.height.x1||!isNaN(c.height.x2)&&0!==c.height.x2||0!==c.sandboxWidth.x1||0!==c.sandboxHeight.x1||0!==c.left.x1||0!==c.top.x1},_doAnimationLayout:function(c,e){var b=c._parent._measuredWidth,o=c._parent._measuredHeight,
h=c._measuredRunningHeight,k=e.width.x1*b+e.width.x2;return{width:k,height:e.height.x1*o+e.height.x2*(o-h)+e.height.x3,left:e.left.x1*b+e.left.x2*k+e.left.x3,top:e.top.x1*o+e.top.x2+h}},_measureNode:function(c,e,b,t){c._needsMeasuring=!1;var h=t.getValueType,k=t.computeValue,r=t._getWidth(c,e.width),a=h(r),r=k(r,a),j=t._getHeight(c,e.height),c=h(j),j=k(j,c),d=e.left,n=h(d),d=k(d,n),f=e.center&&e.center.x,p=h(f),f=k(f,p),l=e.right,i=h(l),l=k(l,i),q=e.top,m=h(q),q=k(q,m),e=e.bottom,h=h(e),k=k(e,h),
g,s=b.width,e=b.height,u=b.sandboxWidth,w=b.sandboxHeight,v=b.left,x=b.top,b=g=0;a===o.SIZE?b=g=NaN:a===o.FILL?(b=1,"%"===n?b-=d:"#"===n?g=-d:"%"===i?b-=l:"#"===i&&(g=-l)):"%"===a?b=r:"#"===a?g=r:"%"===n?"%"===p?b=2*(f-d):"#"===p?(b=-2*d,g=2*f):"%"===i?b=1-d-l:"#"===i&&(b=1-d,g=-l):"#"===n?"%"===p?(b=2*f,g=-2*d):"#"===p?g=2*(f-d):"%"===i?(b=1-l,g=-d):"#"===i&&(b=1,g=-l-d):"%"===p?"%"===i?b=2*(l-f):"#"===i&&(b=-2*f,g=2*l):"#"===p&&("%"===i?(b=2*l,g=-2*f):"#"===i&&(g=2*(l-f)));s.x1=b;s.x2=g;u.x1="%"===
i?l:0;u.x2="#"===i?l:0;b=g=a=0;c===o.SIZE?b=g=a=NaN:c===o.FILL?(g=1,"%"===m&&(b=-q),"#"===m&&(a=-q),"%"===h&&(b=-k),"#"===h&&(a=-k)):"%"===c?b=j:"#"===c&&(a=j);e.x1=b;e.x2=g;e.x3=a;b=g=0;"%"===m&&(b=q);"#"===m&&(g=q);"%"===h&&(b+=k);"#"===h&&(g+=k);w.x1=b;w.x2=g;b=g=a=0;if("%"===n)b=d;else if("#"===n)a=d;else if("%"===p)b=f,g=-0.5;else if("#"===p)g=-0.5,a=f;else if("%"===i)b=1-l,g=-1;else if("#"===i)b=1,g=-1,a=-l;else switch(t._defaultHorizontalAlignment){case "center":b=0.5;g=-0.5;break;case "end":b=
1,g=-1}v.x1=b;v.x2=g;v.x3=a;x.x1="%"===m?q:0;x.x2="#"===m?q:0},_defaultHorizontalAlignment:"center",_defaultVerticalAlignment:"start"})});