define(["Ti/_/Layouts/Base","Ti/_/declare","Ti/UI","Ti/_/lang","Ti/_/style"],function(y,z,p,A){var t=A.isDef,u=Math.round;return z("Ti._.Layouts.ConstrainingHorizontal",y,{_doLayout:function(b,d,c,l,k){var i={width:0,height:0},s=b._children,a,g=0,h,f,n,q,j,r,o=[],m=0;j=0;var e=s.length;r=this._measureNode;for(g=0;g<e;g++)a=b._children[g],!a._alive||!a.domNode?this.handleInvalidState(a,b):a._markedForLayout&&((a._preLayout&&a._preLayout(d,c,l,k)||a._needsMeasuring)&&r(a,a,a._layoutCoefficients,this),
h=a._layoutCoefficients,f=h.width,0===f.x2||isNaN(f.x2)?(n=h.height,q=h.sandboxWidth,h=n.x1*c+n.x2,f=f.x1*d+f.x2*(d-m)+f.x3,n=a._getContentSize?a._getContentSize(f,h):a._layout._doLayout(a,isNaN(f)?d:f-a._borderLeftWidth-a._borderRightWidth,isNaN(h)?c:h-a._borderTopWidth-a._borderBottomWidth,isNaN(f),isNaN(h)),isNaN(f)&&(f=n.width+a._borderLeftWidth+a._borderRightWidth),isNaN(h)&&(h=n.height+a._borderTopWidth+a._borderBottomWidth),q=a._measuredSandboxWidth=q.x1*d+q.x2+f,m+=q,a._measuredWidth=f,a._measuredHeight=
h):j++);l=d-m;m=Math.floor(l/j);for(g=0;g<e;g++)a=b._children[g],a._markedForLayout&&(h=a._layoutCoefficients,f=h.width,0!==f.x2&&!isNaN(f.x2)&&(n=h.height,q=h.sandboxWidth,h=n.x1*c+n.x2,f=f.x1*d+f.x2*(g<e-1?m:l-m*(j-1))+f.x3,n=a._getContentSize?a._getContentSize(f,h):a._layout._doLayout(a,isNaN(f)?d:f-a._borderLeftWidth-a._borderRightWidth,isNaN(h)?c:h-a._borderTopWidth-a._borderBottomWidth,isNaN(f),isNaN(h)),isNaN(f)&&(f=n.width+a._borderLeftWidth+a._borderRightWidth),isNaN(h)&&(h=n.height+a._borderTopWidth+
a._borderBottomWidth),a._measuredWidth=f,a._measuredHeight=h,a._measuredSandboxWidth=q.x1*d+q.x2+f));for(g=m=0;g<e;g++)a=b._children[g],a._measuredRunningWidth=m,a._markedForLayout&&(h=a._layoutCoefficients,j=h.sandboxHeight,l=h.top,r=h.left,k&&0!==l.x1?o.push(a):(h=a._measuredHeight,l=a._measuredTop=l.x1*c+l.x2*h+l.x3,j=a._measuredSandboxHeight=j.x1*c+j.x2+h+(isNaN(l)?0:l),j>i.height&&(i.height=j)),a._measuredLeft=r.x1*d+r.x2+m),m+=a._measuredSandboxWidth;i.width=m;e=o.length;for(g=0;g<e;g++)a=o[g],
j=a._layoutCoefficients.sandboxHeight,j=a._measuredSandboxHeight=j.x1*c+j.x2+a._measuredHeight,j>i.height&&(i.height=j);for(g=0;g<e;g++)a=o[g],l=a._layoutCoefficients.top,h=a._measuredHeight,j=a._measuredSandboxHeight,j>i.height&&(i.height=j),l=a._measuredTop=l.x1*i.height+l.x2*h+l.x3,a._measuredSandboxHeight+=isNaN(l)?0:l;e=s.length;for(g=0;g<e;g++)a=s[g],a._markedForLayout&&(p._elementLayoutCount++,a=s[g],b=a.domNode.style,b.zIndex=a.zIndex,b.left=u(a._measuredLeft)+"px",b.top=u(a._measuredTop)+
"px",b.width=u(a._measuredWidth-a._borderLeftWidth-a._borderRightWidth)+"px",b.height=u(a._measuredHeight-a._borderTopWidth-a._borderBottomWidth)+"px",a._markedForLayout=!1,a.fireEvent("postlayout"));return this._computedSize=i},_getWidth:function(b,d){!t(d)&&(d=b._defaultWidth);return d===p.INHERIT?b._parent._parent?b._parent._parent._layout._getWidth(b._parent,b._parent.width)===p.SIZE?p.SIZE:p.FILL:p.FILL:d},_getHeight:function(b,d){!t(d)&&2>t(b.top)+t(b.center&&b.center.y)+t(b.bottom)&&(d=b._defaultHeight);
return d===p.INHERIT?b._parent._parent?b._parent._parent._layout._getHeight(b._parent,b._parent.height)===p.SIZE?p.SIZE:p.FILL:p.FILL:d},_isDependentOnParent:function(b){b=b._layoutCoefficients;return!isNaN(b.width.x1)&&0!==b.width.x1||!isNaN(b.width.x2)&&0!==b.width.x2||!isNaN(b.height.x1)&&0!==b.height.x1||0!==b.sandboxWidth.x1||0!==b.sandboxHeight.x1||0!==b.left.x1||0!==b.top.x1},_doAnimationLayout:function(b,d){var c=b._parent._measuredWidth,l=b._parent._measuredHeight,k=b._measuredRunningWidth,
i=d.height.x1*l+d.height.x2;return{width:d.width.x1*c+d.width.x2*(c-k)+d.width.x3,height:i,left:d.left.x1*c+d.left.x2+k,top:d.top.x1*l+d.top.x2*i+d.top.x3}},_measureNode:function(b,d,c,l){b._needsMeasuring=!1;var k=l.getValueType,i=l.computeValue,s=l._getWidth(b,d.width),a=k(s),s=i(s,a),g=l._getHeight(b,d.height),b=k(g),h=i(g,b),f=d.left,g=k(f),f=i(f,g),n=d.right,q=k(n),n=i(n,q),j=d.top,r=k(j),j=i(j,r),o=d.center&&d.center.y,m=k(o),o=i(o,m),d=d.bottom,k=k(d),i=i(d,k),e,d=c.width,t=c.height,u=c.sandboxWidth,
w=c.sandboxHeight,x=c.left,v=c.top,c=e=0;b===p.SIZE?c=e=NaN:b===p.FILL?(c=1,"%"===r?c-=j:"#"===r?e=-j:"%"===k?c-=i:"#"===k&&(e=-i)):"%"===b?c=h:"#"===b?e=h:"%"===r?"%"===m?c=2*(o-j):"#"===m?(c=-2*j,e=2*o):"%"===k?c=1-j-i:"#"===k&&(c=1-j,e=-i):"#"===r?"%"===m?(c=2*o,e=-2*j):"#"===m?e=2*(o-j):"%"===k?(c=1-i,e=-j):"#"===k&&(c=1,e=-i-j):"%"===m?"%"===k?c=2*(i-o):"#"===k&&(c=-2*o,e=2*i):"#"===m&&("%"===k?(c=2*i,e=-2*o):"#"===k&&(e=2*(i-o)));t.x1=c;t.x2=e;w.x1="%"===k?i:0;w.x2="#"===k?i:0;c=e=b=0;a===p.SIZE?
c=e=b=NaN:a===p.FILL?(e=1,"%"===g&&(c=-f),"#"===g&&(b=-f),"%"===q&&(c=-n),"#"===q&&(b=-n)):"%"===a?c=s:"#"===a&&(b=s);d.x1=c;d.x2=e;d.x3=b;c=e=0;"%"===g&&(c=f);"#"===g&&(e=f);"%"===q&&(c+=n);"#"===q&&(e+=n);u.x1=c;u.x2=e;c=e=b=0;if("%"===r)c=j;else if("#"===r)b=j;else if("%"===m)c=o,e=-0.5;else if("#"===m)e=-0.5,b=o;else if("%"===k)c=1-i,e=-1;else if("#"===k)c=1,e=-1,b=-i;else switch(l._defaultVerticalAlignment){case "center":c=0.5;e=-0.5;break;case "end":c=1,e=-1}v.x1=c;v.x2=e;v.x3=b;x.x1="%"===
g?f:0;x.x2="#"===g?f:0},_defaultHorizontalAlignment:"start",_defaultVerticalAlignment:"center"})});