define("Ti/_/Layouts/Base,Ti/_/declare,Ti/API,Ti/UI,Ti/_/lang,Ti/_/style".split(","),function(z,A,B,p,C){var y=C.isDef,x=Math.round,D=Math.floor,E=Math.ceil;return A("Ti._.Layouts.Horizontal",z,{_doLayout:function(c,b,d,m,g){var k={width:0,height:0},s=c._children,a,i=0,e,h,f,l,t,r,j,o=0,n=0,u=[[]],v=[],w=[],q=s.length;t=this._measureNode;for(i=0;i<q;i++)a=c._children[i],!a._alive||!a.domNode?this.handleInvalidState(a,c):(a._measuredRunningWidth=n,a._markedForLayout&&((a._preLayout&&a._preLayout(b,
d,m,g)||a._needsMeasuring)&&t(a,a,a._layoutCoefficients,this),e=a._layoutCoefficients,h=e.width,f=e.height,l=e.sandboxWidth,r=e.left,h=h.x1*b+h.x2*(b-n)+h.x3,e=0===f.x2?f.x1*d+f.x3:NaN,isNaN(h)||isNaN(f.x1)?(j=a._getContentSize?a._getContentSize(h,e):a._layout._doLayout(a,isNaN(h)?b:h-a._borderLeftWidth-a._borderRightWidth,isNaN(e)?d:e-a._borderTopWidth-a._borderBottomWidth,isNaN(h),isNaN(e)),isNaN(h)&&(h=j.width+a._borderLeftWidth+a._borderRightWidth),isNaN(f.x1)&&(e=j.height+a._borderTopWidth+a._borderBottomWidth),
a._childrenLaidOut=!0,0!==f.x2&&!isNaN(f.x2)&&(B.warn("Child of width SIZE and height FILL detected in a horizontal layout. Performance degradation may occur."),a._childrenLaidOut=!1)):a._childrenLaidOut=!1,a._measuredWidth=h,a._measuredHeight=e,f=a._measuredSandboxWidth=l.x1*b+l.x2+h,e=r.x1*b+r.x2+n,!m&&D(f+n)>E(b)&&(u.push([]),e-=n,n=0),a._measuredLeft=e,u[u.length-1].push(a),n+=f,n>k.width&&(k.width=n)));q=u.length;for(i=0;i<q;i++){m=u[i];g=0;n=m.length;for(c=0;c<n;c++)a=m[c],a._markedForLayout&&
(e=a._layoutCoefficients,l=e.top,f=e.height,t=e.sandboxHeight,e=a._measuredHeight,isNaN(e)&&(a._measuredHeight=e=f.x1*d+f.x2*(d-o)+f.x3),a._childrenLaidOut||(h=a._measuredWidth,a._childrenLaidOut=!0,a._layout._doLayout(a,isNaN(h)?b:h-a._borderLeftWidth-a._borderRightWidth,isNaN(e)?d:e-a._borderTopWidth-a._borderBottomWidth,isNaN(h),isNaN(e))),0!==l.x2?(w.push(a),f=o):a._measuredTop=f=l.x1*d+l.x3*e+l.x4+o,a._measuredSandboxHeight=a=t.x1*d+t.x2+e+f-o,g<a&&(g=a));v.push(g);o+=g}o=0;q=u.length;for(i=
0;i<q;i++){m=u[i];g=v[i];n=m.length;for(c=0;c<n;c++)a=m[c],a._measuredRunningHeight=o,a._measuredRowHeight=g,~w.indexOf(a)&&a._markedForLayout&&(e=a._measuredHeight,l=a._layoutCoefficients.top,a._measuredTop=l.x1*d+l.x2*g+l.x3*e+l.x4+o);o+=g}k.height=o;q=s.length;for(i=0;i<q;i++)a=s[i],a._markedForLayout&&(p._elementLayoutCount++,a=s[i],b=a.domNode.style,b.zIndex=a.zIndex,b.left=x(a._measuredLeft)+"px",b.top=x(a._measuredTop)+"px",b.width=x(a._measuredWidth-a._borderLeftWidth-a._borderRightWidth)+
"px",b.height=x(a._measuredHeight-a._borderTopWidth-a._borderBottomWidth)+"px",a._markedForLayout=!1,a.fireEvent("postlayout"));return this._computedSize=k},_getWidth:function(c,b){!y(b)&&(b=c._defaultWidth);return b===p.INHERIT?c._parent._parent?c._parent._parent._layout._getWidth(c._parent,c._parent.width)===p.SIZE?p.SIZE:p.FILL:p.FILL:b},_getHeight:function(c,b){!y(b)&&(b=c._defaultHeight);return b===p.INHERIT?c._parent._parent?c._parent._parent._layout._getHeight(c._parent,c._height)===p.SIZE?
p.SIZE:p.FILL:p.FILL:b},_isDependentOnParent:function(c){c=c._layoutCoefficients;return!isNaN(c.width.x1)&&0!==c.width.x1||!isNaN(c.width.x2)&&0!==c.width.x2||!isNaN(c.height.x1)&&0!==c.height.x1||!isNaN(c.height.x2)&&0!==c.height.x2||0!==c.sandboxWidth.x1||0!==c.sandboxHeight.x1||0!==c.left.x1||0!==c.top.x1},_doAnimationLayout:function(c,b){var d=c._parent._measuredWidth,m=c._parent._measuredHeight,g=c._measuredRunningWidth,k=c._measuredRunningHeight;return{width:b.width.x1*d+b.width.x2*(d-g)+b.width.x3,
height:b.height.x1*m+b.height.x2*(m-k)+b.height.x3,left:b.left.x1*d+b.left.x2+g,top:b.top.x1*m+b.top.x2*c._measuredRowHeight+b.top.x3*c._measuredHeight+b.top.x4+k}},_measureNode:function(c,b,d,m){c._needsMeasuring=!1;var g=m.getValueType,k=m.computeValue,s=m._getWidth(c,b.width),a=g(s),s=k(s,a),i=m._getHeight(c,b.height),c=g(i),i=k(i,c),e=b.left,h=g(e),e=k(e,h),f=b.right,l=g(f),t=k(f,l),r=b.top,f=g(r),r=k(r,f),b=b.bottom,g=g(b),k=k(b,g),j,o=d.width,n=d.height,u=d.sandboxWidth,v=d.sandboxHeight,w=
d.left,q=d.top,d=b=j=0;a===p.SIZE?d=b=j=NaN:a===p.FILL?(b=1,"%"===h&&(d=-e),"#"===h&&(j=-e),"%"===l&&(d=-t),"#"===l&&(j=-t)):"%"===a?d=s:"#"===a&&(j=s);o.x1=d;o.x2=b;o.x3=j;d=b=0;"%"===h&&(d=e);"#"===h&&(b=e);"%"===l&&(d+=t);"#"===l&&(b+=t);u.x1=d;u.x2=b;d=b=j=0;c===p.SIZE?d=b=j=NaN:c===p.FILL?(b=1,"%"===f&&(d=-r),"#"===f&&(j=-r)):"%"===c?d=i:"#"===c&&(j=i);n.x1=d;n.x2=b;n.x3=j;v.x1="%"===g?k:0;v.x2="#"===g?k:0;w.x1="%"===h?e:0;w.x2="#"===h?e:0;d=b=j=a=0;if("%"===f)d=r;else if("#"===f)a=r;else if("%"===
g)d=1-k,j=-1;else if("#"===g)d=1,j=-1,a=-k;else switch(m._defaultRowAlignment){case "center":b=0.5;j=-0.5;break;case "end":b=1,j=-1}q.x1=d;q.x2=b;q.x3=j;q.x4=a},_defaultHorizontalAlignment:"start",_defaultVerticalAlignment:"start",_defaultRowAlignment:"center"})});