define("Ti/_/browser,Ti/_/declare,Ti/UI/View,Ti/_/lang,Ti/_/dom,Ti/_/style,Ti/UI,Ti/_/event".split(","),function(y,z,o,D,h,A){var f=A.set,i=h.unitize,v=h.calculateDistance,k=require.on,m={webkit:"webkitTransitionEnd",trident:"msTransitionEnd",gecko:"transitionend",presto:"oTransitionEnd"}[y.runtime]||"transitionEnd",B=100,C=100;return z("Ti._.UI.KineticScrollView",o,{_initKineticScrollView:function(b,c,d,e){function f(){u=(new Date).getTime();p=u-m;m=u;l++?(q=(q*(l-1)+l*(h-o)/p)/2/l,r=(r*(l-1)+l*
(i-w)/p)/2/l):(q=(h-j)/p,r=(i-n)/p)}var a=this,j,n,h,i,s,t,m,u,p,o,w,l,q,r,x;a._currentTranslationX=0;a._currentTranslationY=0;a._horizontalElastic="horizontal"===c||"both"===c;a._verticalElastic="vertical"===c||"both"===c;("horizontal"===d||"both"===d)&&this._createHorizontalScrollBar();("vertical"===d||"both"===d)&&this._createVerticalScrollBar();a._add(a._contentContainer=b);k(a,"draggingstart",function(d){if(this.scrollingEnabled){r=q=void 0;j=a._currentTranslationX;n=a._currentTranslationY;l=
0;m=(new Date).getTime();s=a._minTranslationX=Math.min(0,a._measuredWidth-a._borderLeftWidth-a._borderRightWidth-a._contentContainer._measuredWidth);t=a._minTranslationY=Math.min(0,a._measuredHeight-a._borderTopWidth-a._borderBottomWidth-a._contentContainer._measuredHeight);var c=a._measuredWidth,f=a._measuredHeight,e=b._measuredWidth,g=b._measuredHeight;a._startScrollBars({x:-a._currentTranslationX/(e-c),y:-a._currentTranslationY/(g-f)},{x:c/e,y:f/g});a._handleDragStart&&a._handleDragStart(d)}});
k(a,"dragging",function(c){a.scrollingEnabled&&(h=j+c.distanceX,i=n+c.distanceY,f(),a._setTranslation(o=h,w=i),a._updateScrollBars({x:-a._currentTranslationX/(b._measuredWidth-a._measuredWidth),y:-a._currentTranslationY/(b._measuredHeight-a._measuredHeight)}),a._handleDrag&&a._handleDrag(c))});k(a,"draggingcancel",function(b){a.scrollingEnabled&&(a._animateToPosition(j,n,400+0.3*v(j,n,a._currentTranslationX,a._currentTranslationY),"ease-in-out",function(){a._handleDragCancel&&a._handleDragCancel(b)}),
a._endScrollBars(),a._handleDragCancel&&a._handleDragCancel(b))});k(a,"draggingend",function(b){if(a.scrollingEnabled){h=j+b.distanceX;i=n+b.distanceY;f();var c=a._currentTranslationX,d=a._currentTranslationY,e;0<c?(c=0,e=1):c<s&&(c=s,e=1);0<d?(d=0,e=1):d<t&&(d=t,e=1);e?a._animateToPosition(c,d,200,"ease-out",function(){a._handleDragEnd&&a._handleDragEnd(b)}):a._handleDragEnd&&a._handleDragEnd(b,q,r)}});e&&(this._disconnectMouseWheelEvent=k(a.domNode,"mousewheel",function(c){if(a.scrollingEnabled){var d=
b._measuredWidth-a._measuredWidth,e=b._measuredHeight-a._measuredHeight,f=-a._currentTranslationX,g=-a._currentTranslationY;s=a._minTranslationX=Math.min(0,a._measuredWidth-a._borderLeftWidth-a._borderRightWidth-a._contentContainer._measuredWidth);t=a._minTranslationY=Math.min(0,a._measuredHeight-a._borderTopWidth-a._borderBottomWidth-a._contentContainer._measuredHeight);a._startScrollBars({x:f/d,y:g/e},{x:a._measuredWidth/b._measuredWidth,y:a._measuredHeight/b._measuredHeight});a._setTranslation(Math.min(0,
Math.max(a._minTranslationX,-f+c.wheelDeltaX)),Math.min(0,Math.max(a._minTranslationY,-g+c.wheelDeltaY)));a._updateScrollBars({x:f/d,y:g/e});clearTimeout(x);x=setTimeout(function(){a._endScrollBars()},500);a._handleMouseWheel&&a._handleMouseWheel()}}))},destroy:function(){this._disconnectMouseWheelEvent&&this._disconnectMouseWheelEvent();o.prototype.destroy.apply(this,arguments)},_animateToPosition:function(b,c,d,e,g){var a=this,j=a._contentContainer,h=j.domNode;1>v(a._currentTranslationX,a._currentTranslationY,
b,c)?(a._setTranslation(b,c),g()):(f(h,"transition","all "+d+"ms "+e),setTimeout(function(){a._setTranslation(b,c);a._animateScrollBars({x:-a._currentTranslationX/(j._measuredWidth-a._measuredWidth),y:-a._currentTranslationY/(j._measuredHeight-a._measuredHeight)},d,e)},1),k.once(h,m,function(){f(h,"transition","");g&&g()}))},_setTranslation:function(b,c){function d(a){return B*(-1/(a/C+1)+1)}var e=this._contentContainer,g=this._minTranslationX,a=this._minTranslationY,h=this._horizontalElastic&&!this.disableBounce&&
this._measuredWidth<e._measuredWidth,e=this._verticalElastic&&!this.disableBounce&&this._measuredHeight<e._measuredHeight;0<b?b=h?d(b):0:b<g&&(b=h?g-d(g-b):g);0<c?c=e?d(c):0:c<a&&(c=e?a-d(a-c):a);f(this._contentContainer.domNode,"transform","translate("+(this._currentTranslationX=b)+"px, "+(this._currentTranslationY=c)+"px)")},_createHorizontalScrollBar:function(){this._horizontalScrollBar=h.create("div",{className:"TiUIScrollBar",style:{position:"absolute",zIndex:2147483647,border:"3px solid #555",
borderRadius:"3px",height:"0px",bottom:"0px",opacity:0}},this.domNode)},_destroyHorizontalScrollBar:function(){this._cancelPreviousAnimation();h.destroy(this._horizontalScrollBar)},_createVerticalScrollBar:function(){this._verticalScrollBar=h.create("div",{className:"TiUIScrollBar",style:{position:"absolute",zIndex:2147483647,border:"3px solid #555",borderRadius:"3px",width:"0px",right:"0px",opacity:0}},this.domNode)},_destroyVerticalScrollBar:function(){this._cancelPreviousAnimation();h.destroy(this._verticalScrollBar)},
_cancelPreviousAnimation:function(){this._isScrollBarActive&&(f(this._horizontalScrollBar,"transition",""),f(this._verticalScrollBar,"transition",""),clearTimeout(this._horizontalScrollBarTimer),clearTimeout(this._verticalScrollBarTimer))},_startScrollBars:function(b,c){this._cancelPreviousAnimation();if(this._horizontalScrollBar&&1>c.x&&0<c.x){var d=b.x,e=this._measuredWidth;0>d&&(d=0);1<d&&(d=1);this._horizontalScrollBarWidth=(e-6)*c.x;10>this._horizontalScrollBarWidth&&(this._horizontalScrollBarWidth=
10);f(this._horizontalScrollBar,{opacity:0.5,left:i(d*(e-this._horizontalScrollBarWidth-6)),width:i(this._horizontalScrollBarWidth)});this._isScrollBarActive=!0}this._verticalScrollBar&&1>c.y&&0<c.y&&(d=b.y,e=this._measuredHeight,0>d&&(d=0),1<d&&(d=1),this._verticalScrollBarHeight=(e-6)*c.y,10>this._verticalScrollBarHeight&&(this._verticalScrollBarHeight=10),f(this._verticalScrollBar,{opacity:0.5,top:i(d*(e-this._verticalScrollBarHeight-6)),height:i(this._verticalScrollBarHeight)}),this._isScrollBarActive=
!0)},_updateScrollBars:function(b){this._isScrollBarActive&&(this._horizontalScrollBar&&f(this._horizontalScrollBar,"left",i(Math.max(0,Math.min(1,b.x))*(this._measuredWidth-this._horizontalScrollBarWidth-6))),this._verticalScrollBar&&f(this._verticalScrollBar,"top",i(Math.max(0,Math.min(1,b.y))*(this._measuredHeight-this._verticalScrollBarHeight-6))))},_animateScrollBars:function(b,c,d){var e=this,g=e._horizontalScrollBar,a=e._verticalScrollBar;e._isScrollBarActive&&(g&&(f(g,"transition","all "+
c+"ms "+d),k.once(g,m,function(){f(g,"transition","")})),a&&(f(a,"transition","all "+c+"ms "+d),k.once(a,m,function(){f(a,"transition","")})),setTimeout(function(){e._updateScrollBars(b)},1))},_endScrollBars:function(){var b=this;setTimeout(function(){if(b._isScrollBarActive){if(b._horizontalScrollBar){var c=b._horizontalScrollBar;c&&(f(c,"transition","all 1s ease-in-out"),setTimeout(function(){f(c,"opacity",0);b._horizontalScrollBarTimer=setTimeout(function(){b._isScrollBarActive=!1;f(c,"transition",
"")},500)},0))}if(b._verticalScrollBar){var d=b._verticalScrollBar;d&&(f(d,"transition","all 1s ease-in-out"),setTimeout(function(){f(d,"opacity",0);b._verticalScrollBarTimer=setTimeout(function(){b._isScrollBarActive=!1;f(d,"transition","")},500)},0))}}},10)},properties:{scrollingEnabled:!0}})});