package_assets: off
template_function: _.template
javascripts:
  app:
    - public/javascripts/pack/jquery-1.4.4.min.js
    - public/javascripts/pack/jquery-ui-1.8.9.custom.min.js
    - public/javascripts/pack/json2.js
    - public/javascripts/pack/underscore-1.1.4.js
    - public/javascripts/pack/backbone.js
    - public/javascripts/application.js
    - public/javascripts/models/*.js
    
    - public/javascripts/collections/*.js
    - public/javascripts/views/*.js
 
    - public/javascripts/**/*.js
    - app/views/**/*.jst
    
   

stylesheets:
  app:
    - public/stylesheets/*.css
