define("Ti/_/declare,Ti/_/dom,Ti/_/event,Ti/_/lang,Ti/App/Properties,Ti/Geolocation,Ti/Map,Ti/UI/View,Ti/Utils".split(","),function(n,l,o,k,w,i,p,m,x){function r(a){var b=c.MapTypeId;switch(a){case p.HYBRID_TYPE:return b.HYBRID;case p.SATELLITE_TYPE:return b.SATELLITE;case p.TERRAIN_TYPE:return b.TERRAIN}return b.ROADMAP}var q=k.isDef,y=require.mix,s=require.on,t=m.prototype._handleTouchEvent,z={latitude:39.828175,longitude:-98.5795,latitudeDelta:30.137412,longitudeDelta:63.235658},c,j,e,h={"0":"red",
1:"green",2:"purple"},u,v=Ti.deferStart(),n=n("Ti.Map.View",m,{constructor:function(){this.properties.__values__.annotations=[];this._annotationMap={};this._routes=[];this.fireEvent("loading")},postscript:function(){var a=this.region,b=this._gmap=new c.Map(this.domNode,{disableDefaultUI:!0,zoom:2,zoomControl:!0,center:new c.LatLng(a.latitude,a.longitude),mapTypeId:r(this.mapType)});this._boundsEvt=j.addListener(b,"bounds_changed",k.hitch(this,"_fitRegion"));this._updateMap(a,1);this._updateUserLocation(this.userLocation);
this.annotations.forEach(this._createMarker,this);this._annotationEvents=[]},destroy:function(){o.off(this._annotationEvents);j.removeListener(this._boundsEvt);j.clearInstanceListeners(this._gmap);this.removeAllAnnotations();this._gmap=null;m.prototype.destroy.apply(this,arguments)},addAnnotation:function(a){a&&("Ti.Map.Annotation"===a.declaredClass||(a=new Annotation(a)),~this.annotations.indexOf(a)||this._createMarker(a),a.title&&(this._annotationMap[a.title]=a))},addAnnotations:function(a){a&&
a.forEach(this.addAnnotation,this)},addRoute:function(a){if(a&&(a.points||[]).length)a.pline=new c.Polyline({map:this._gmap,path:a.points.map(function(a){return new c.LatLng(a.latitude,a.longitude)}),strokeColor:a.color||"#000",strokeWeight:a.width||1}),this._routes.push(a)},deselectAnnotation:function(a){require.is(a,"String")&&(a=this._annotationMap[a]);a&&e&&e.widgetId===a.widgetId&&this._hide(a)},removeAllAnnotations:function(){for(e&&e.close();this.annotations.length;)this.removeAnnotation(this.annotations[0])},
removeAnnotation:function(a){require.is(a,"String")&&(a=this._annotationMap[a]);if(a){var b=this.properties.__values__.annotations,d=b.indexOf(a);e&&this._hide(a);j.removeListener(a.evt);a.marker.setMap(null);delete a.marker;a.destroy();~d&&b.splice(d,1)}},removeAnnotations:function(a){a.forEach(function(a){this.removeAnnotation(a)},this)},removeRoute:function(a){if(a&&a.name)for(var b=this._routes,d=0;d<b.length;d++)b[d].name===a.name&&(a.pline.setMap(null),delete a.pline,b.splice(d--,1))},selectAnnotation:function(a){require.is(a,
"String")&&(a=this._annotationMap[a]);a&&this._show(a)},setLocation:function(a){a&&(this.region=a);q(a.animate)&&(this.animated=a.animate);q(a.animated)&&(this.animated=a.animated);q(a.regionFit)&&(this.regionFit=a.regionFit);this._updateMap(a)},zoom:function(a){var b=this._gmap;b.setZoom(b.getZoom()+a)},_show:function(a,b){if(a&&(!e||e.widgetId!==a.widgetId)){var d=this,A=a.widgetId,f,g=l.create("div",{className:"TiMapAnnotation"}),h=g,i={annotation:h,leftButton:a.leftButton&&l.create("img",{className:"TiMapAnnotationLeftButton",
src:a.leftButton},g),rightButton:a.rightButton&&l.create("img",{className:"TiMapAnnotationRightButton",src:a.rightButton},g),dummy:(g=l.create("div",{className:"TiMapAnnotationContent"},g))&&0,title:l.create("h1",{innerHTML:a._getTitle()},g),subtitle:l.create("p",{innerHTML:a._getSubtitle()},g)},k,g=function(){k||(k=1)&&d._dispatchEvents(a,b)};o.off(d._annotationEvents);for(f in i)(function(b,c){c&&d._annotationEvents.push(s(c,"click",function(c){o.stop(c);d._hide(a,b)}))})(f,i[f]);d._annotationEvents.push(s(a,
"update",this,function(b){if(e.widgetId===A){var c=b.property,f=b.value,g=this._annotationMap;switch(c){case "title":case "subtitle":i[c].innerHTML=f;delete g[b.oldValue];f&&(g[f]=a);break;case "leftButton":case "rightButton":i[c].src=f;break;case "image":case "pincolor":b=d._getMarkerImage(a),a.marker.setIcon(b[0]),a.marker.setShadow(b[1]||null)}}}));e?(g(),e.setContent(h)):(e=new c.InfoWindow({content:h}),j.addListener(e,"domready",g),j.addListener(e,"closeclick",function(){d._hide(a,"annotation")}));
e.open(d._gmap,a.marker);e.widgetId=a.widgetId}},_hide:function(a,b){if(!b||!~b.indexOf("Button"))e.close(),e.widgetId=0;this._dispatchEvents(a,b)},_dispatchEvents:function(a,b){var d=this.annotations.indexOf(a),c={annotation:a,clicksource:b=b||"pin",index:d,latitude:a.latitude,longitude:a.longitude,map:this,subtitle:a._getSubtitle(),title:a._getTitle()};t.call(this,"singletap",c);t.call(this,"click",c);a._onclick(this,d,b)},_getMarkerImage:function(a){var b=h[a.pincolor|0],d;a.image&&("Ti.Blob"===
a.image.declaredClass?(b=h[a=x.md5HexDigest(d=a.image.toString())])||(b=h[a]=[new c.MarkerImage(d)]):(b=h[a.image])||(b=h[a.image]=[new c.MarkerImage(a.image)]));return b},_createMarker:function(a){var b=this._getMarkerImage(a);a.evt=j.addListener(a.marker=new c.Marker({map:this._gmap,icon:b[0],shadow:b[1],position:new c.LatLng(a.latitude,a.longitude),optimized:!1,title:a._getTitle(),animation:a.animate&&c.Animation.DROP}),"click",k.hitch(this,function(){this[e&&e.widgetId===a.widgetId?"_hide":"_show"](a)}));
this.properties.__values__.annotations.push(a)},_fitRegion:function(){var a=this.constants,b=this._gmap,d=b.getCenter(),c=b.getBounds(),b=c.getNorthEast(),f=c.getSouthWest(),c=a.latitudeDelta=b.lat()-f.lat(),a=a.longitudeDelta=b.lng()-f.lng(),d={latitude:d.lat(),longitude:d.lng(),latitudeDelta:c,longitudeDelta:a};this.regionFit&&(this.properties.__values__.region=d);this._initialized||(this._initialized=1,this.fireEvent("complete"));this.fireEvent("regionChanged",d)},_updateMap:function(a,b){var d=
this._gmap;if(d){var e=!b&&this.animated,f=a.latitudeDelta/2,g=a.longitudeDelta/2;d[e?"panTo":"setCenter"](new c.LatLng(a.latitude,a.longitude));d[e?"panToBounds":"fitBounds"](new c.LatLngBounds(new c.LatLng(a.latitude-f,a.longitude-g),new c.LatLng(a.latitude+f,a.longitude+g)))}},_updateUserLocation:function(a){if(this._gmap&&(a||this._locationInited))this._locationInited=1,i[a?"addEventListener":"removeEventListener"]("location",k.hitch(this,function(a){var d=this._locationMarker,e=a.coords,f=a.code;
e?(a=new c.LatLng(e.latitude,e.longitude),d?d.setPosition(a):this._locationMarker=new c.Marker({map:this._gmap,icon:u,position:a})):"code"in a&&Ti.API.warn("Geolocation error: "+(f===i.ERROR_DENIED?"permission denied":f===i.ERROR_TIMEOUT?"timeout":f===i.ERROR_LOCATION_UNKNOWN?"position unavailable":"unknown"))})),i.locationServicesEnabled?(!a||this._locationMarker)&&this._locationMarker.setVisible(a):(Ti.API.warn("Geolocation services unavailable"),this.properties.__values__.userLocation=!1)},_handleTouchEvent:function(a,
b){/(click|singletap)/.test(a)||m.prototype._handleTouchEvent.apply(this,arguments)},constants:{latitudeDelta:0,longitudeDelta:0},properties:{animated:!1,annotations:{set:function(a){a=a.filter(function(a){return a&&"Ti.Map.Annotation"===a.declaredClass});this._gmap&&(this.removeAllAnnotations(),a.forEach(this._createMarker,this));return a}},mapType:{set:function(a){this._gmap&&this._gmap.setMapTypeId(r(a));return a}},region:{set:function(a,b){return y({},z,b,a)},post:function(a,b){a!==b&&this._updateMap(a)},
value:null},regionFit:!0,userLocation:{post:function(a){this._updateUserLocation(a)},value:!1}}});window.TiMapViewInit=function(){function a(a,b,h){return new c.MarkerImage(d+"marker_"+a+".png",new c.Size(b,34),new e(h,0),new e(10,34))}c=google.maps;j=c.event;var b,d="themes/"+require.config.ti.theme+"/Map/",e=c.Point;for(b in h)h[b]=[a(h[b],20,0),a(h[b],37,20)];u=new c.MarkerImage(d+"location.png",new c.Size(22,22),new e(0,0),new e(11,11));v()};require(["//maps.googleapis.com/maps/api/js?key="+w.getString("ti.map.apikey",
"")+"&sensor=true&callback=TiMapViewInit"],0,v);return n});